Place.create(name: 'Viet Village', value: 9.00)
Place.create(name: 'Butcher', value: 6)
Place.create(name: 'Hummus', value: 9.50)
Place.create(name: 'Cheap pizza place', value: 5)
Place.create(name: 'Expensive pizza place', value: 10)
Place.create(name: 'Neta Mexican Street Food', value: 7)
Place.create(name: 'Curry', value: 4)
Place.create(name: 'Burger', value: 7)
Place.create(name: 'Sushi', value: 8)
Place.create(name: 'Habba Habba', value: 8)
Place.create(name: 'Fishfabrik', value: 10)
Place.create(name: 'Die Schule', value: 9)
